/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schema.json
export type FormSettings = {
  _id: string;
  _type: "formSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  notificationRecipients?: Array<string>;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: {
    servicesLabel?: string;
    servicesHref?: string;
    resourcesLabel?: string;
    links?: Array<
      {
        _key: string;
      } & Link
    >;
    ctaButton?: Link;
  };
  companySetup?: {
    title?: string;
    href?: string;
    listingTitle?: string;
    listingTitleAccent?: string;
    description?: string;
    items?: Array<
      {
        _key: string;
      } & Link
    >;
  };
  serviceCategories?: Array<{
    title?: string;
    href?: string;
    description?: string;
    items?: Array<
      {
        _key: string;
      } & Link
    >;
    showInFooter?: boolean;
    listingTitle?: string;
    listingTitleAccent?: string;
    _type: "serviceCategory";
    _key: string;
  }>;
  resourceLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  footer?: {
    description?: string;
    companyLinks?: Array<
      {
        _key: string;
      } & Link
    >;
  };
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type Link = {
  _type: "link";
  linkType?: "page" | "custom";
  page?: ServiceReference;
  section?: string;
  href?: string;
  label?: string;
  description?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    imageAlt?: string;
  };
  story?: {
    eyebrow?: string;
    title?: string;
    paragraphs?: Array<{
      text?: string;
      _key: string;
    }>;
  };
  whyClients?: {
    title?: string;
    description?: string;
    items?: Array<string>;
  };
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  journey?: {
    eyebrow?: string;
    title?: string;
    milestones?: Array<{
      year?: string;
      title?: string;
      description?: string;
      _key: string;
    }>;
  };
  values?: {
    eyebrow?: string;
    title?: string;
    items?: Array<{
      title?: string;
      description?: string;
      _key: string;
    }>;
  };
  commitment?: {
    eyebrow?: string;
    title?: string;
    paragraphs?: Array<{
      text?: string;
      _key: string;
    }>;
  };
  cta?: Cta;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  keywords?: Array<string>;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Cta = {
  _type: "cta";
  title?: string;
  description?: string;
  primaryLabel?: string;
  primaryHref?: string;
  secondaryLabel?: string;
  secondaryHref?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type TeamMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teamMember";
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    headline?: string;
    headlineAccent?: string;
    subheadline?: string;
    primaryCtaLabel?: string;
    primaryCtaHref?: string;
    secondaryCtaLabel?: string;
    secondaryCtaHref?: string;
    bgImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  about?: {
    eyebrow?: string;
    title?: string;
    titleSpan?: string;
    description?: string;
    buttonText?: string;
    buttonHref?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    stats?: Array<
      {
        _key: string;
      } & Stat
    >;
  };
  services?: {
    eyebrow?: string;
    title?: string;
    items?: Array<{
      number?: string;
      title?: string;
      description?: string;
      href?: string;
      subItems?: Array<
        {
          _key: string;
        } & Link
      >;
      _type: "serviceRow";
      _key: string;
    }>;
  };
  testimonialsSection?: {
    hidden?: boolean;
    eyebrow?: string;
    title?: string;
    titleAccent?: string;
    rows?: 1 | 2;
    speed?: number;
    ctaLabel?: string;
    ctaHref?: string;
  };
  testimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
  team?: {
    hidden?: boolean;
    eyebrow?: string;
    title?: string;
    members?: Array<
      {
        _key: string;
      } & TeamMemberReference
    >;
  };
  faq?: {
    hidden?: boolean;
    eyebrow?: string;
    title?: string;
    items?: Array<
      {
        _key: string;
      } & FaqItem
    >;
  };
  seo?: Seo;
};

export type FormSubmission = {
  _id: string;
  _type: "formSubmission";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: "new" | "contacted" | "closed";
  name?: string;
  email?: string;
  phone?: string;
  service?: string;
  message?: string;
  sourcePage?: string;
  submittedAt?: string;
  emailNotified?: boolean;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: string;
  order?: number;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  author?: string;
  position?: string;
  text?: string;
  order?: number;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?:
    | "company-setup"
    | "license-services"
    | "visa-immigration"
    | "finance-banking"
    | "pro-government"
    | "notary-services";
  order?: number;
  listing?: {
    summary?: string;
    badge?: string;
  };
  hero?: {
    title?: string;
    description?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    imageAlt?: string;
  };
  overview?: {
    eyebrow?: string;
    title?: string;
    description?: string;
    highlights?: Array<string>;
    expectationTitle?: string;
    expectationDescription?: string;
  };
  stats?: Array<
    {
      _key: string;
    } & Stat
  >;
  deliverables?: {
    eyebrow?: string;
    title?: string;
    items?: Array<
      {
        _key: string;
      } & Deliverable
    >;
  };
  process?: {
    eyebrow?: string;
    title?: string;
    items?: Array<
      {
        _key: string;
      } & ProcessStep
    >;
  };
  faqs?: {
    eyebrow?: string;
    title?: string;
    items?: Array<
      {
        _key: string;
      } & FaqItem
    >;
  };
  cta?: Cta;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Deliverable = {
  _type: "deliverable";
  title?: string;
  description?: string;
  anchor?: string;
};

export type ProcessStep = {
  _type: "processStep";
  step?: string;
  title?: string;
  description?: string;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: string;
};

export type Stat = {
  _type: "stat";
  value?: string;
  label?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | FormSettings
  | Navigation
  | ServiceReference
  | Link
  | SanityImageAssetReference
  | AboutPage
  | Seo
  | Cta
  | SanityImageCrop
  | SanityImageHotspot
  | TestimonialReference
  | TeamMemberReference
  | Homepage
  | FormSubmission
  | TeamMember
  | Testimonial
  | Service
  | Slug
  | Deliverable
  | ProcessStep
  | FaqItem
  | Stat
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: navigationQuery
// Query: *[_type == "navigation"][0]{  header{ servicesLabel, servicesHref, resourcesLabel, links[]{ "label": coalesce(label, page->title), "href": select(  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),  href), description }, ctaButton{ "label": coalesce(label, page->title), "href": select(  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),  href), description } },  companySetup{ title, href, description, items[]{ "label": coalesce(label, page->title), "href": select(  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),  href), description } },  serviceCategories[]{ title, href, description, showInFooter, items[]{ "label": coalesce(label, page->title), "href": select(  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),  href), description } },  resourceLinks[]{ "label": coalesce(label, page->title), "href": select(  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),  href), description },  footer{ description, companyLinks[]{ "label": coalesce(label, page->title), "href": select(  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),  href), description } }}
export type NavigationQueryResult = {
  header: {
    servicesLabel: string | null;
    servicesHref: string | null;
    resourcesLabel: string | null;
    links: Array<{
      label: string | null;
      href: string | null;
      description: string | null;
    }> | null;
    ctaButton: {
      label: string | null;
      href: string | null;
      description: string | null;
    } | null;
  } | null;
  companySetup: {
    title: string | null;
    href: string | null;
    description: string | null;
    items: Array<{
      label: string | null;
      href: string | null;
      description: string | null;
    }> | null;
  } | null;
  serviceCategories: Array<{
    title: string | null;
    href: string | null;
    description: string | null;
    showInFooter: boolean | null;
    items: Array<{
      label: string | null;
      href: string | null;
      description: string | null;
    }> | null;
  }> | null;
  resourceLinks: Array<{
    label: string | null;
    href: string | null;
    description: string | null;
  }> | null;
  footer: {
    description: string | null;
    companyLinks: Array<{
      label: string | null;
      href: string | null;
      description: string | null;
    }> | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: servicesListingQuery
// Query: *[_type == "navigation"][0]{  companySetup{ title, listingTitle, listingTitleAccent, items[]{  "label": coalesce(label, page->title),  "href": select(  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),  href),  "summary": coalesce(page->listing.summary, page->hero.description, description),  "badge": page->listing.badge,  "image": page->hero.image{ ..., asset->{ _id, url, metadata { lqip, dimensions } } }} },  serviceCategories[]{ title, href, listingTitle, listingTitleAccent, items[]{  "label": coalesce(label, page->title),  "href": select(  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),  href),  "summary": coalesce(    description,    page->deliverables.items[anchor == ^.section][0].description,    page->listing.summary,    page->hero.description  ),  "badge": page->listing.badge,  "image": page->hero.image{ ..., asset->{ _id, url, metadata { lqip, dimensions } } }} }}
export type ServicesListingQueryResult = {
  companySetup: {
    title: string | null;
    listingTitle: string | null;
    listingTitleAccent: string | null;
    items: Array<{
      label: string | null;
      href: string | null;
      summary: string | null;
      badge: string | null;
      image: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
  } | null;
  serviceCategories: Array<{
    title: string | null;
    href: string | null;
    listingTitle: string | null;
    listingTitleAccent: string | null;
    items: Array<{
      label: string | null;
      href: string | null;
      summary: string | null;
      badge: string | null;
      image: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: homepageQuery
// Query: *[_type == "homepage"][0]{  hero{ ..., bgImage{ ..., asset->{ _id, url, metadata { lqip, dimensions } } } },  about{ ..., image{ ..., asset->{ _id, url, metadata { lqip, dimensions } } } },  services{ eyebrow, title, items[]{ number, title, description, href, subItems[]{ "label": coalesce(label, page->title), "href": select(  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),  href), description } } },  testimonialsSection{ hidden, eyebrow, title, titleAccent, rows, speed, ctaLabel, ctaHref },  testimonials[]->{ _id, author, position, text },  team{ hidden, eyebrow, title, members[]->{ _id, name, role, image{ ..., asset->{ _id, url, metadata { lqip, dimensions } } } } },  faq{ hidden, eyebrow, title, items[]{ question, answer } },  seo}
export type HomepageQueryResult = {
  hero: {
    headline?: string;
    headlineAccent?: string;
    subheadline?: string;
    primaryCtaLabel?: string;
    primaryCtaHref?: string;
    secondaryCtaLabel?: string;
    secondaryCtaHref?: string;
    bgImage: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  about: {
    eyebrow?: string;
    title?: string;
    titleSpan?: string;
    description?: string;
    buttonText?: string;
    buttonHref?: string;
    image: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    stats?: Array<
      {
        _key: string;
      } & Stat
    >;
  } | null;
  services: {
    eyebrow: string | null;
    title: string | null;
    items: Array<{
      number: string | null;
      title: string | null;
      description: string | null;
      href: string | null;
      subItems: Array<{
        label: string | null;
        href: string | null;
        description: string | null;
      }> | null;
    }> | null;
  } | null;
  testimonialsSection: {
    hidden: boolean | null;
    eyebrow: string | null;
    title: string | null;
    titleAccent: string | null;
    rows: 1 | 2 | null;
    speed: number | null;
    ctaLabel: string | null;
    ctaHref: string | null;
  } | null;
  testimonials: Array<{
    _id: string;
    author: string | null;
    position: string | null;
    text: string | null;
  }> | null;
  team: {
    hidden: boolean | null;
    eyebrow: string | null;
    title: string | null;
    members: Array<{
      _id: string;
      name: string | null;
      role: string | null;
      image: {
        asset: {
          _id: string;
          url: string | null;
          metadata: {
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
          } | null;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
    }> | null;
  } | null;
  faq: {
    hidden: boolean | null;
    eyebrow: string | null;
    title: string | null;
    items: Array<{
      question: string | null;
      answer: string | null;
    }> | null;
  } | null;
  seo: Seo | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: sitemapServicesQuery
// Query: *[_type == "service" && defined(slug.current)]{  "slug": slug.current,  _updatedAt}
export type SitemapServicesQueryResult = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: serviceSlugsQuery
// Query: *[_type == "service" && defined(slug.current)]{  "slug": slug.current}
export type ServiceSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: serviceBySlugQuery
// Query: *[_type == "service" && slug.current == $slug][0]{  title,  "slug": slug.current,  category,  hero{ title, description, imageAlt, image{ ..., asset->{ _id, url, metadata { lqip, dimensions } } } },  overview{ eyebrow, title, description, highlights, expectationTitle, expectationDescription },  stats[]{ value, label },  deliverables{ eyebrow, title, items[]{ anchor, title, description } },  process{ eyebrow, title, items[]{ step, title, description } },  faqs{ eyebrow, title, items[]{ question, answer } },  cta{ title, description, primaryLabel, primaryHref, secondaryLabel, secondaryHref },  seo{ title, description, keywords, ogImage{ ..., asset->{ _id, url, metadata { lqip, dimensions } } } }}
export type ServiceBySlugQueryResult = {
  title: string | null;
  slug: string | null;
  category:
    | "company-setup"
    | "finance-banking"
    | "license-services"
    | "notary-services"
    | "pro-government"
    | "visa-immigration"
    | null;
  hero: {
    title: string | null;
    description: string | null;
    imageAlt: string | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  overview: {
    eyebrow: string | null;
    title: string | null;
    description: string | null;
    highlights: Array<string> | null;
    expectationTitle: string | null;
    expectationDescription: string | null;
  } | null;
  stats: Array<{
    value: string | null;
    label: string | null;
  }> | null;
  deliverables: {
    eyebrow: string | null;
    title: string | null;
    items: Array<{
      anchor: string | null;
      title: string | null;
      description: string | null;
    }> | null;
  } | null;
  process: {
    eyebrow: string | null;
    title: string | null;
    items: Array<{
      step: string | null;
      title: string | null;
      description: string | null;
    }> | null;
  } | null;
  faqs: {
    eyebrow: string | null;
    title: string | null;
    items: Array<{
      question: string | null;
      answer: string | null;
    }> | null;
  } | null;
  cta: {
    title: string | null;
    description: string | null;
    primaryLabel: string | null;
    primaryHref: string | null;
    secondaryLabel: string | null;
    secondaryHref: string | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
    keywords: Array<string> | null;
    ogImage: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage"][0]{  hero{ eyebrow, title, description, imageAlt, image{ ..., asset->{ _id, url, metadata { lqip, dimensions } } } },  story{ eyebrow, title, paragraphs[]{ text } },  whyClients{ title, description, items },  stats[]{ value, label },  journey{ eyebrow, title, milestones[]{ year, title, description } },  values{ eyebrow, title, items[]{ title, description } },  commitment{ eyebrow, title, paragraphs[]{ text } },  cta{ title, description, primaryLabel, primaryHref, secondaryLabel, secondaryHref },  seo{ title, description }}
export type AboutPageQueryResult = {
  hero: {
    eyebrow: string | null;
    title: string | null;
    description: string | null;
    imageAlt: string | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  story: {
    eyebrow: string | null;
    title: string | null;
    paragraphs: Array<{
      text: string | null;
    }> | null;
  } | null;
  whyClients: {
    title: string | null;
    description: string | null;
    items: Array<string> | null;
  } | null;
  stats: Array<{
    value: string | null;
    label: string | null;
  }> | null;
  journey: {
    eyebrow: string | null;
    title: string | null;
    milestones: Array<{
      year: string | null;
      title: string | null;
      description: string | null;
    }> | null;
  } | null;
  values: {
    eyebrow: string | null;
    title: string | null;
    items: Array<{
      title: string | null;
      description: string | null;
    }> | null;
  } | null;
  commitment: {
    eyebrow: string | null;
    title: string | null;
    paragraphs: Array<{
      text: string | null;
    }> | null;
  } | null;
  cta: {
    title: string | null;
    description: string | null;
    primaryLabel: string | null;
    primaryHref: string | null;
    secondaryLabel: string | null;
    secondaryHref: string | null;
  } | null;
  seo: {
    title: string | null;
    description: string | null;
  } | null;
} | null;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "navigation"][0]{\n  header{ servicesLabel, servicesHref, resourcesLabel, links[]{ "label": coalesce(label, page->title), "href": select(\n  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),\n  href\n), description }, ctaButton{ "label": coalesce(label, page->title), "href": select(\n  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),\n  href\n), description } },\n  companySetup{ title, href, description, items[]{ "label": coalesce(label, page->title), "href": select(\n  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),\n  href\n), description } },\n  serviceCategories[]{ title, href, description, showInFooter, items[]{ "label": coalesce(label, page->title), "href": select(\n  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),\n  href\n), description } },\n  resourceLinks[]{ "label": coalesce(label, page->title), "href": select(\n  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),\n  href\n), description },\n  footer{ description, companyLinks[]{ "label": coalesce(label, page->title), "href": select(\n  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),\n  href\n), description } }\n}': NavigationQueryResult;
    '*[_type == "navigation"][0]{\n  companySetup{ title, listingTitle, listingTitleAccent, items[]{\n  "label": coalesce(label, page->title),\n  "href": select(\n  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),\n  href\n),\n  "summary": coalesce(page->listing.summary, page->hero.description, description),\n  "badge": page->listing.badge,\n  "image": page->hero.image{ ..., asset->{ _id, url, metadata { lqip, dimensions } } }\n} },\n  serviceCategories[]{ title, href, listingTitle, listingTitleAccent, items[]{\n  "label": coalesce(label, page->title),\n  "href": select(\n  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),\n  href\n),\n  "summary": coalesce(\n    description,\n    page->deliverables.items[anchor == ^.section][0].description,\n    page->listing.summary,\n    page->hero.description\n  ),\n  "badge": page->listing.badge,\n  "image": page->hero.image{ ..., asset->{ _id, url, metadata { lqip, dimensions } } }\n} }\n}': ServicesListingQueryResult;
    '*[_type == "homepage"][0]{\n  hero{ ..., bgImage{ ..., asset->{ _id, url, metadata { lqip, dimensions } } } },\n  about{ ..., image{ ..., asset->{ _id, url, metadata { lqip, dimensions } } } },\n  services{ eyebrow, title, items[]{ number, title, description, href, subItems[]{ "label": coalesce(label, page->title), "href": select(\n  linkType == "page" && defined(page) => "/services/" + page->slug.current + select(defined(section) && section != "" => "#" + section, ""),\n  href\n), description } } },\n  testimonialsSection{ hidden, eyebrow, title, titleAccent, rows, speed, ctaLabel, ctaHref },\n  testimonials[]->{ _id, author, position, text },\n  team{ hidden, eyebrow, title, members[]->{ _id, name, role, image{ ..., asset->{ _id, url, metadata { lqip, dimensions } } } } },\n  faq{ hidden, eyebrow, title, items[]{ question, answer } },\n  seo\n}': HomepageQueryResult;
    '*[_type == "service" && defined(slug.current)]{\n  "slug": slug.current,\n  _updatedAt\n}': SitemapServicesQueryResult;
    '*[_type == "service" && defined(slug.current)]{\n  "slug": slug.current\n}': ServiceSlugsQueryResult;
    '*[_type == "service" && slug.current == $slug][0]{\n  title,\n  "slug": slug.current,\n  category,\n  hero{ title, description, imageAlt, image{ ..., asset->{ _id, url, metadata { lqip, dimensions } } } },\n  overview{ eyebrow, title, description, highlights, expectationTitle, expectationDescription },\n  stats[]{ value, label },\n  deliverables{ eyebrow, title, items[]{ anchor, title, description } },\n  process{ eyebrow, title, items[]{ step, title, description } },\n  faqs{ eyebrow, title, items[]{ question, answer } },\n  cta{ title, description, primaryLabel, primaryHref, secondaryLabel, secondaryHref },\n  seo{ title, description, keywords, ogImage{ ..., asset->{ _id, url, metadata { lqip, dimensions } } } }\n}': ServiceBySlugQueryResult;
    '*[_type == "aboutPage"][0]{\n  hero{ eyebrow, title, description, imageAlt, image{ ..., asset->{ _id, url, metadata { lqip, dimensions } } } },\n  story{ eyebrow, title, paragraphs[]{ text } },\n  whyClients{ title, description, items },\n  stats[]{ value, label },\n  journey{ eyebrow, title, milestones[]{ year, title, description } },\n  values{ eyebrow, title, items[]{ title, description } },\n  commitment{ eyebrow, title, paragraphs[]{ text } },\n  cta{ title, description, primaryLabel, primaryHref, secondaryLabel, secondaryHref },\n  seo{ title, description }\n}': AboutPageQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
